allinfo/urls.py
from django.urls import path,include
from .views import home,all_dept,dept_teacher,teacher_detail,all_teacher

app_name= 'allinfo'

urlpatterns = [
    path('',home,name='home'),
    path('dept/',all_dept,name='dept'),
    path('all/teacher/',all_teacher,name='all_teach'),
    path('teacher/<int:id>/',dept_teacher,name='dept_tech'),
    path('detail/teacher/<int:id>/',teacher_detail,name='tech_detail'),
    
]

routine_admin/urls.py
from django.urls import path
from .views import (homepage,all_dept,create_depart,update_dept,delete_dept,
                    all_teacher,create_teacher,update_teacher,delete_teacher,days_table,
                    times_table,display_routine,create_routine,update_routine,delete_routine )

app_name = 'admin_page'

urlpatterns = [
    path('',homepage,name='admin-home'),
    path('admin/department/',all_dept,name='admin-dept'),
    path('admin/teacher/',all_teacher,name='admin-teacher'),
    path('admin/create/department/',create_depart,name='admin-dept-create'),
    path('admin/create/teacher/',create_teacher,name='admin-teacher-create'),
    path('admin/routine/days/',days_table,name='admin-routine-days'),
    path('admin/routine/times/',times_table,name='admin-routine-times'),
    path('admin/routine/display_routine/',display_routine,name='admin-routine-display'),
    path('admin/routine/create/room/',create_routine,name='admin-room-create'),

    path('admin/update/department/<int:id>/',update_dept,name='admin-dept-update'),
    path('admin/delete/department/<int:id>/',delete_dept,name='admin-dept-delete'),
    path('admin/update/teacher/<int:id>/',update_teacher,name='admin-teacher-update'),
    path('admin/delete/teacher/<int:id>/',delete_teacher,name='admin-teacher-delete'),
    path('admin/update/routine/<int:id>/',update_routine,name='admin-routine-update'),
    path('admin/delete/routine/<int:id>/',delete_routine,name='admin-routine-delete'),


]

routine_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('allinfo.urls')),
    path('routine/admin/',include('routine_admin.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

routine_admin/models.py
from django.db import models

# Create your models here.

routine_admin/views.py
from django.shortcuts import render,redirect,get_object_or_404
from allinfo.models import All_department,Techer_info
from allinfo.forms import DepartmentForm , TeacherinfoForm
from django.contrib import messages
from routine_info.forms import RoutineDaysForm,RoutineTimeForm,RoutineTimeWithInitial
from routine_info.models import Room_with_na,Routine_days,Routine_time
from django.contrib.admin.views.decorators import staff_member_required
# Create your views here.
@staff_member_required
def homepage(request):
    template_name = "routine_admin/home.html"
    all_teacher = Techer_info.objects.all().count()
    all_department = All_department.objects.all().count()
    all_routine = Room_with_na.objects.all().count()
    
    context = {
        'all_teacher': all_teacher,
        'all_department': all_department,
        'all_routine': all_routine,
    }
    return render(request,template_name,context)

@staff_member_required
def all_dept(request):
    template_name = "routine_admin/department/all_dept.html"
    all_dept = All_department.objects.all()

    

    context = {
        'all_dept': all_dept,
        
    }
    return render(request,template_name,context)

@staff_member_required
def create_depart(request):
    template_name = "routine_admin/department/create_dept.html"
    if request.method == 'POST':
        #get from values
        title = request.POST['title']
        name = request.POST['name']


        dept = All_department.objects.create(title=title,name=name)
                       
        dept.save()
        messages.success(request,'Department Created')
        return redirect('admin_page:admin-dept')
    
    context ={
        'value': 'Create',
    }

       
    
    return render(request,template_name,context)

@staff_member_required
def update_dept(request,id):
    template_name = "routine_admin/department/create_dept.html"
    instance = get_object_or_404(All_department,id=id)

    if request.method == 'POST':
        #get from values
        title = request.POST['title']
        name = request.POST['name']


        dept = All_department.objects.create(title=title,name=name)
                       
        dept.save()
        messages.success(request,'Department Updated')
        return redirect('admin_page:admin-dept')

    context = {
        'instance':instance,
        'value': 'Update',
    }
    return render(request,template_name,context)

@staff_member_required
def delete_dept(request,id):
    # template_name = "routine_admin/department/all_dept.html"
    instance = get_object_or_404(All_department,id=id)
    instance.delete()
    messages.warning(request,'Department Deleted')
    return redirect('admin_page:admin-dept')


############### Teacher info Section ######
@staff_member_required
def all_teacher(request):
    template_name = "routine_admin/teacher/all_teacher.html"
    all_teach = Techer_info.objects.all()

    

    context = {
        'all_teach': all_teach,
        
    }
    return render(request,template_name,context)

@staff_member_required
def create_teacher(request):
    template_name = "routine_admin/teacher/create_teacher.html"
    all_dept = All_department.objects.all()
    form = TeacherinfoForm(request.POST, request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        # instance.user   = request.user
        instance.save()
        return redirect('admin_page:admin-teacher')
    
    context ={
        'value': 'Create',
        'all_dept':all_dept,
        'form':form
    }

       
    
    return render(request,template_name,context)


@staff_member_required
def update_teacher(request,id):
    template_name = "routine_admin/teacher/create_teacher.html"
    instance = get_object_or_404(Techer_info,id=id)
    form = TeacherinfoForm(request.POST or None,instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        
        instance.save()
        return redirect('admin_page:admin-teacher')
    
    context ={
        'value': 'update',
        
        'form':form,
    }

       
    
    return render(request,template_name,context)


@staff_member_required
def delete_teacher(request,id):
    # template_name = "routine_admin/department/all_dept.html"
    instance = get_object_or_404(Techer_info,id=id)
    instance.delete()
    messages.warning(request,'Department Deleted')
    return redirect('admin_page:admin-teacher')


# Create days
@staff_member_required
def days_table(request):
    template_name = "routine_admin/routine/days/day.html"
    all_days = Routine_days.objects.all()

    context = {
        'all_days': all_days,
    }
    return render(request,template_name,context)


# Create Time
@staff_member_required
def times_table(request):
    template_name = 'routine_admin/routine/times/time.html'
    all_times = Routine_time.objects.all()

    context = {
        'all_times': all_times,
    }
    return render(request,template_name,context)


# Create routine with Initial
@staff_member_required
def display_routine(request):
    template_name = 'routine_admin/routine/routine.html'
    all_routine = Room_with_na.objects.all()

    context = {
        'all_routine' : all_routine,
    }
    return render(request,template_name,context)


@staff_member_required
def create_routine(request):
    template_name = "routine_admin/routine/create_routine.html"
    # all_dept = All_department.objects.all()
    form = RoutineTimeWithInitial(request.POST, request.FILES)
    if form.is_valid():
        instance = form.save(commit=False)
        # instance.user   = request.user
        instance.save()
        return redirect('admin_page:admin-routine-display')
    
    context ={
        'value': 'Create',
        
        'form':form,
    }
    return render(request,template_name,context)


@staff_member_required
def update_routine(request,id):
    template_name = "routine_admin/routine/create_routine.html"
    instance = get_object_or_404(Room_with_na,id=id)
    form = RoutineTimeWithInitial(request.POST or None,instance=instance)

    if form.is_valid():
        instance = form.save(commit=False)
        
        instance.save()
        return redirect('admin_page:admin-routine-display')
    
    context ={
        'value': 'update',
        
        'form':form,
    }

       
    
    return render(request,template_name,context)


@staff_member_required
def delete_routine(request,id):
    # template_name = "routine_admin/department/all_dept.html"
    instance = get_object_or_404(Room_with_na,id=id)
    instance.delete()
    messages.warning(request,'Routine Deleted')
    return redirect('admin_page:admin-routine-display')

routine_admin/templates/routine_admin/dashboard.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Admin | Panel</title>

  <link rel="shortcut icon" href="https://pngimage.net/wp-content/uploads/2018/06/logo-admin-png-7.png" type="image/x-icon">


  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <!-- Latest compiled and minified CSS -->
<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"> -->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-dark sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="">
        <div class="sidebar-brand-icon rotate-n-15">
          <!-- <img src="{% static 'new_home_static/images/auction.png' %}" alt=""> -->
          <!-- <i class="fas fa-laugh-wink"></i> -->
        </div>
        <div class="sidebar-brand-text mx-3"><sup>DIU</sup>Teacher Profile </div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin_page:admin-home' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Admin Panel</span></a>
      </li>
      <hr class="sidebar-divider">

      <div class="sidebar-heading">
        Department Info
      </div>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#ucollapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-address-book"></i>
          <span>Department</span>
        </a>
        <div id="ucollapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Department Info:</h6>
            <a class="collapse-item" href="{% url 'admin_page:admin-dept' %}">All Department</a>
            <a class="collapse-item" href="{% url 'admin_page:admin-dept-create' %}">Create New Department</a>

          


          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Teacher Info
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-globe-europe"></i>
          <span>Teacher Detail</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">All Pages:</h6>
            <a class="collapse-item" href="{% url 'admin_page:admin-teacher' %}">All Teacher</a>
            <a class="collapse-item" href="{% url 'admin_page:admin-teacher-create' %}">Create New Teacher</a>
            <!-- <h6 class="collapse-header">Live Auction:</h6>
            <a class="collapse-item" href="#">Live Products</a> -->


          </div>
        </div>
      </li>

   

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Routine
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-folder"></i>
          <span>Routine System</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
           
            <a class="collapse-item" href="{% url 'admin_page:admin-routine-days' %}">Days</a>
            <a class="collapse-item" href="{% url 'admin_page:admin-routine-times' %}">Time</a>
            
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Add Routine</h6>
            <a class="collapse-item" href="{% url 'admin_page:admin-routine-display' %}">All Routine</a>
            <a class="collapse-item" href="{% url 'admin_page:admin-room-create' %}">Create Routine</a>
            <!-- <a class="collapse-item" href="#">Product(Premium)</a> -->


           
          </div>
        </div>
      </li>

    

    

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
        

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    











          



          






            





            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user}}
                    <i class="fas fa-user-tie"></i>
                </span>
                <!-- <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60"> -->
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                
                
              
                
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">







































{% block content %}





{% endblock%}












































      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy;Teacher Profile.com 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="login.html">Logout</a>
        </div>
      </div>
    </div>
  </div>



  <!-- Bootstrap core JavaScript-->
  <script src="{%static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

  <!-- Page level plugins -->


</body>

</html>

routine_admin/templates/routine_admin/home.html
{% extends 'routine_admin/dashboard.html' %}


{% block content %}


          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
                <a href="{% url 'allinfo:home' %}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Go to Main Website</a>
              </div>
    
              <!-- Content Row -->
              <div class="row">




                  <div class="col-xl-3 col-md-6 mb-4">
                      <div class="card border-left-info shadow h-100 py-2">
                        <div class="card-body">
                          <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Total Teacher</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800">{{all_teacher}}</div>
                            </div>
                            <div class="col-auto text-info">
                                <i class="fas fa-users fa-2x text-info-300"></i>
                              <!-- <i class="fas fa-comments fa-2x text-warning-300"></i> -->
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                 


    
                <!-- Earnings (Monthly) Card Example -->
                <div class="col-xl-3 col-md-6 mb-4">
                  <div class="card border-left-danger shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Total Department</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">{{all_department}}</div>
                        </div>
                        <div class="col-auto text-danger">
                              <i class="fas fa-book fa-2x text-danger-300"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>




                   <!-- Earnings (Monthly) Card Example -->
                   <div class="col-xl-3 col-md-6 mb-4">
                      <div class="card border-left-success shadow h-100 py-2">
                        <div class="card-body">
                          <div class="row no-gutters align-items-center">
                            <div class="col mr-2">
                              <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Total Routine Added</div>
                              <div class="h5 mb-0 font-weight-bold text-gray-800">{{all_routine}}</div>
                            </div>
                            <div class="col-auto text-success">
                              <!-- <i class="fas fa-calendar fa-2x text-gray-300"></i> -->
                              <!-- <i class="fas fa-book fa-2x text-success-300"></i> -->
                              <i class="fab fa-studiovinari fa-2x text-success-300"></i>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                
    
 
    
              </div>
    
              <!-- Content Row -->
    
          
    
    
            </div>
            <!-- /.container-fluid -->

{% endblock %}