allinfo/urls.py
from django.urls import path,include
from .views import home,all_dept,dept_teacher,teacher_detail,all_teacher

app_name= 'allinfo'

urlpatterns = [
    path('',home,name='home'),
    path('dept/',all_dept,name='dept'),
    path('all/teacher/',all_teacher,name='all_teach'),
    path('teacher/<int:id>/',dept_teacher,name='dept_tech'),
    path('detail/teacher/<int:id>/',teacher_detail,name='tech_detail'),
    
]

routine_system/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('allinfo.urls')),
    path('routine/admin/',include('routine_admin.urls')),
    
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>DIU Teacher Profile</title>

    <link rel="shortcut icon" href="https://seeklogo.com/images/E/education-colour-pencil-logo-F199DAED6C-seeklogo.com.png" type="image/x-icon">

    <link rel="stylesheet" href="https://bootswatch.com/4/lumen/bootstrap.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css">

    <style>
            .footer {
               
               left: 0;
               bottom: 0;
               width: 100%;
               background-color: #4582EC;
               color: white;
               text-align: center;
            }
            </style>
</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'allinfo:home' %}"><span><i class="fas fa-chalkboard-teacher"></i></span> DIU Teacher Profile</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarColor01">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link btn btn-danger" href="{% url 'allinfo:dept' %}"> <i class="fas fa-building"></i> Go to all Dept</a>
            </li>
            
          </ul>
       
        </div>
      </nav>



    {% block content %}

    

    {% endblock %}


    <div class="footer p-3">
        <p>
            Presented by:
               <span><a class="text-white" href="#">ifirozy.com</a></span> 
               &
               <span><a href="" class="text-white">sharmin.com</a></span>
        </p>
      </div>


    <!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}


{% block content %}




<div class="jumbotron" style="margin-bottom: 0px !important;">
    <h1 class="display-3 text-center">Welcome to our website!</h1>
    <p class="text-center">Go search teacher initial and blah blah ki likhbo</p>
    <hr class="my-4 ">
    
    <p class="text-center">

        <div class="container">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                        <form class="text-center" action="{% url 'allinfo:all_teach' %}" method="GET">
                                <div class="form-group">
                                        <label class="col-form-label" for="inputDefault">Type Initial</label>
                                        <input name="q" type="text" class="form-control" placeholder="type initial" id="inputDefault">
                                      </div>
                
                
                                      <div class="form-group">
                                            <label for="exampleSelect1">Select dept</label>
                                            <select class="form-control" id="exampleSelect1">
                                              <option>cse</option>
                                              <option>bba</option>
                                              <option>eee</option>
                                              <option>multi</option>
                                              <option>commerce</option>
                                            </select>
                                          </div>
                
                                            <button class="btn btn-success" type="submit"><i class="fas fa-search"></i> Search</button>
                                          <!-- <input type="submit" value="search" class="btn btn-success"> -->
                        </form>
                </div>
            </div>
        </div>

            
      <!-- <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a> -->
    </p>
  </div>



{% endblock %}